#!/bin/bash
tput reset
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -e /usr/lib/sshplus ]] && rm -rf /bin/menu > /dev/null 2>&1
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;37m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;37m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;37m["
done
echo -e "\033[1;37m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}

IP=$(cat /etc/IP)
x="ok"

velocity () {
aguarde () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
${comando[0]} > /dev/null 2>&1
${comando[1]} > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;37mAGUARDE \033[1;37m- \033[1;37m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;37m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;37mAGUARDE \033[1;37m- \033[1;37m["
done
echo -e "\033[1;37m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
fun_tst () {
speedtest --share > speed --secure
}
echo -e "\E[38;5;18m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\E[38;5;18m┃\E[44;1;37m    TESTANDO A VELOCIDADE DO SERVIDOR    \E[0m\E[38;5;18m┃"
echo -e "\E[38;5;18m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
aguarde 'fun_tst'
clear
echo -e "\E[38;5;18m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\E[38;5;18m┃\E[44;1;37m    TESTANDO A VELOCIDADE DO SERVIDOR    \E[0m\E[38;5;18m┃"
echo -e "\E[38;5;18m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
png=$(cat speed | sed -n '5 p' |awk -F : {'printf $NF'})
down=$(cat speed | sed -n '7 p' |awk -F :  {'print $NF'})
upl=$(cat speed | sed -n '9 p' |awk -F :  {'print $NF'})
lnk=$(cat speed | sed -n '10 p' |awk {'print $NF'})
echo -e "\E[38;5;18m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32mPING (LATENCIA):\033[1;37m$png"
echo -e "\033[1;32mDOWNLOAD:\033[1;37m$down"
echo -e "\033[1;32mUPLOAD:\033[1;37m$upl"
echo -e "\033[1;32mLINK: \E[38;5;33m$lnk"
echo -e "\E[38;5;18m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
rm -rf $HOME/speed
}

#limiter
function limit1 () {
   clear
   echo -e "\n\033[1;32mINICIANDO O LIMITER... \033[0m"
   echo ""
   fun_bar 'screen -dmS limiter limiter' 'sleep 3'
   [[ $(grep -wc "limiter" /etc/autostart) = '0' ]] && {
       echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   } || {
       sed -i '/limiter/d' /etc/autostart
	   echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   }
   echo -e "\n\033[1;32m  LIMITER ATIVO !\033[0m"
   sleep 3
   menu
}
function limit2 () {
   clear
   echo -e "\033[1;32mPARANDO O LIMITER... \033[0m"
   echo ""
   fun_stplimiter () {
      sleep 1
      screen -r -S "limiter" -X quit
      screen -wipe 1>/dev/null 2>/dev/null
      [[ $(grep -wc "limiter" /etc/autostart) != '0' ]] && {
          sed -i '/limiter/d' /etc/autostart
      }
      sleep 1
   }
   fun_bar 'fun_stplimiter' 'sleep 3'
   echo -e "\n\033[1;31m LIMITER PARADO !\033[0m"
   sleep 3
   menu
}
function limit_ssh () {
[[ $(ps x | grep "limiter"|grep -v grep |wc -l) = '0' ]] && limit1 || limit2
}
#onlineapp
function onapp1 () {
   clear
   echo -e "\n\033[1;32mINICIANDO O ONLINE APP... \033[0m"
   echo ""
   apt install apache2 -y > /dev/null 2>&1
   sed -i "s/Listen 80/Listen 8888/g" /etc/apache2/ports.conf >/dev/null 2>&1
   service apache2 restart
   rm -rf /var/www/html/server >/dev/null 2>&1
   mkdir /var/www/html/server >/dev/null 2>&1
   fun_bar 'screen -dmS onlineapp onlineapp' 'sleep 3'
   [[ $(grep -wc "onlineapp" /etc/autostart) = '0' ]] && {
       echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
   } || {
       sed -i '/onlineapp/d' /etc/autostart
	   echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
   }
   IP=$(wget -qO- ipv4.icanhazip.com) >/dev/null 2>&1
   echo -e "\n\033[1;32m  ONLINE APP ATIVO !\033[0m"
   echo -e "\033[1;31m \033[1;33mURL de Usuários Online para usar no App\033[0m"
   echo -e " http://$IP:8888/server/online"
   sleep 10
   menu
}
function onapp2() {
    clear
    echo -e "\033[1;32mPARANDO O ONLINE APP... \033[0m"
    echo ""
    function fun_stponlineapp() {
    # Stop Apache2 if it is running on port 80
    if netstat -tulpn | grep -q ':80.*apache2'; then
        service apache2 stop >/dev/null 2>&1
        sleep 1
    fi

    # Stop Apache2 if it is running on port 8888
    if netstat -tulpn | grep -q ':8888.*apache2'; then
        service apache2 stop >/dev/null 2>&1
        sleep 1
    fi

    # Stop Online App
    screen_pids=$(pgrep -f "onlineapp")
    if [ -n "$screen_pids" ]; then
        for pid in $screen_pids; do
            kill "$pid"
            sleep 1
        done
        screen -wipe >/dev/null
    fi

    # Remove Online App from autostart if present
    [[ $(grep -wc "onlineapp" /etc/autostart) != '0' ]] && {
        sed -i '/onlineapp/d' /etc/autostart
    }
}
    fun_bar 'fun_stponlineapp' 'sleep 3'
    rm -rf /var/www/html/server >/dev/null 2>&1
    echo -e "\n\033[1;31m ONLINE APP PARADO !\033[0m"
    sleep 3
    menu
}

function onapp_ssh() {
    if pgrep -f "onlineapp" > /dev/null; then
        onapp2  # Se está rodando, para
    else
        onapp1  # Se não está rodando, inicia
    fi
}
##
function autoexec () {
   if grep "menu;" /etc/profile > /dev/null; then
      clear
      echo -e "\033[1;32mDesativando auto execução\033[0m"
      offautmenu () {
         sed -i '/menu;/d' /etc/profile
      }
      echo ""
      fun_bar 'offautmenu'
      echo ""
      echo -e "\033[1;31mAuto execução desativado!\033[0m"
      sleep 1.5s
      menu2
   else
      clear
      echo -e "\033[1;32mAtivando auto execução\033[0m"
      autmenu () {
         grep -v "^menu;" /etc/profile > /tmp/tmpass && mv /tmp/tmpass /etc/profile
         echo "menu;" >> /etc/profile
      }
      echo ""
      fun_bar 'autmenu'
      echo ""
      echo -e "\033[1;32mAuto execução ativado!\033[0m"
      sleep 1.5s
      menu2
   fi

}
#menu2
menu2 (){
[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m(ON◉) ") || stsf=$(echo -e "\033[1;31m(OFF) ")
stsf=$(ps x | grep "blockt"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
[[ ! -e /usr/lib/licence ]] && rm -rf /bin > /dev/null 2>&1
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
_onli=$(($_ons + $_onop + $_ondrp))
_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
_usop=$(printf '%-5s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
_core=$(printf '%-5s' "$(grep -c cpu[0-9] /proc/stat)")
_system=$(printf '%-10s' "$system")
_hora=$(printf '%(%H:%M:%S)T')
_onlin=$(printf '%-5s' "$_onli")
_userexp=$(printf '%-5s' "$_expuser")
_tuser=$(printf '%-5s' "$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)")
swap1=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $2'})")
swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
clear
echo -e "\033[1;37mSEU IP 👉 \033[38;5;82m$IP            \033[1;36mTELEGRAM 😎\033 \033[1;37m @WNET"
echo -e "\033[0;34m╔══════════════════════════════════════════════════════════╗\033[0m"
echo -e "\033[0;34m║\E[46;1;37m               
  *╔═══❖•ೋ° °ೋ•❖═══╗*
    █░░▒█   █▄░▒█ █▀▀▀ ▀▀█▀▀
    █▒█▒█   █▒█▒█ █▀▀▀ ░▒█░░
    █▄▀▄█   █░░▀█ █▄▄▄ ░▒█░░
  *╚═══❖•ೋ° °ೋ•❖═══╝*                \E[0m\033[0;34m║" 
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
echo -e "\033[0;34m║\033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM      \033[1;31m \033[1;32m PROCESSADOR        \033[0;34m║" 
echo -e "\033[0;34m║\033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m  \033[1;36mNucleos: \033[1;37m$_core\033[0m     \033[0;34m║" 
echo -e "\033[0;34m║\033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usor \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usop\033[0m      \033[0;34m║" 
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"                                                                            
echo -e "\033[0;34m║\033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser\033[0m       \033[0;34m║"                                                                                                                                                                       
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
echo -e "\033[0;34m║\033[1;32mMEMÓRIA SWAP    \033[1;36mTOTAL: \033[1;37m$swap1  \033[1;36mEM USO: \033[1;37m$swap3  \033[1;36mLIVRE: \033[1;37m$swap2 \033[0;34m║"
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m21\033[0;31m] \033[1;37m• \033[1;37mADICIONAR HOST \033[0;31m       [\033[1;36m28\033[0;31m] \033[1;37m• \033[1;37mMUDAR SENHA ROOT    \033[0;34m  ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m22\033[0;31m] \033[1;37m• \033[1;37mREMOVER HOST \033[0;31m         [\033[1;36m29\033[0;31m] $var01 \033[1;37mATUALIZAR SCRIPT    \033[0;34m   ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m23\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SISTEMA \033[0;31m    [\033[1;36m30\033[0;31m] \033[1;37m• \033[1;37mREMOVER SCRIPT  \033[0;34m      ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m24\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SERVICOS \033[0;31m   [\033[1;36m31\033[0;31m] \033[1;37m• \033[1;37mTCPTWEAKER       \033[0;34m     ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m25\033[0;31m] \033[1;37m• \033[1;37mBLOCK TORRENT $stsf\033[0;31m      [\033[1;36m32\033[0;31m] \033[1;37m• \033[1;37mVOLTAR \033[1;32m<\033[1;33m<\033[0;31m<\033[1;31m   \033[0;34m         ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m26\033[0;31m] \033[1;37m• \033[1;37mAUTO EXECUCAO $autm\033[0;31m      [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mSAIR \033[1;32m<\033[1;33m<\033[0;31m<\033[1;31m     \033[0;34m         ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m27\033[0;31m] \033[1;37m• \033[1;37mBOT DE TESTE $stsbotteste\033[0;31m       [\033[1;36mAA\033[0;31m] \033[1;37m• \033[1;37mAUTO REBOOT (00:00H)  \033[0;34m║"
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╝\033[0m"
echo -ne "\033[0;34m╚➤ \033[0;31m INFORME UMA OPÇÃO \033[1;33m:"; read x
case "$x" in
   21)
   clear
   addhost
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   menu2
   ;;
   22)
   clear
   delhost
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   menu2
   ;;
   23)
   clear
   reiniciarsistema
   ;;
   24)
   clear
   reiniciarservicos
   sleep 3
   ;;
   25)
   blockt
   ;;
   26)
   autoexec
   ;;
   27)
   inst-botteste
   ;;
   28)
   clear
   senharoot
   sleep 3
   ;;
   29)
   attscript
   ;;
   30)
   clear
   delscript
   ;;
   31)
   clear
   tcptweaker.sh
   ;;
   32)
   menu
   ;;
   A|AA)
   autoreboot.sh
   ;;
   0|00)
   echo -e "\033[1;31mSaindo...\033[0m"
   sleep 2
   clear
   exit;
   ;;
   *)
   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
   sleep 2
esac
}
while true $x != "ok"
do
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
_onli=$(($_ons + $_onop + $_ondrp))
_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
_usop=$(printf '%-5s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
_core=$(printf '%-5s' "$(grep -c cpu[0-9] /proc/stat)")
_system=$(printf '%-10s' "$system")
_hora=$(printf '%(%H:%M:%S)T')
_onlin=$(printf '%-5s' "$_onli")
_userexp=$(printf '%-5s' "$_expuser")
_tuser=$(printf '%-5s' "$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)")
[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m(ON ◉ ") || stsf=$(echo -e "\033[1;31m(OFF ○ ") 
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
stsom=$(ps x | grep "shutdown -r 16:00"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○) ")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○)")
swap1=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $2'})")
swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
clear
echo -e "\033[1;37mSEU IP 👉 \033[38;5;82m$IP           \033[1;36mTELEGRAM 😎\033 \033[1;37m @WNET"
echo -e "\033[0;34m╔══════════════════════════════════════════════════════════╗\033[0m"
echo -e "\033[0;34m║\E[46;1;37m                *╔═══❖•ೋ° °ೋ•❖═══╗*
    █░░▒█   █▄░▒█ █▀▀▀ ▀▀█▀▀
    █▒█▒█   █▒█▒█ █▀▀▀ ░▒█░░
    █▄▀▄█   █░░▀█ █▄▄▄ ░▒█░░
  *╚═══❖•ೋ° °ೋ•❖═══╝*                \E[0m\033[0;34m║"
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
echo -e "\033[0;34m║\033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM       \033[1;31m \033[1;32mPROCESSADOR        \033[0;34m║"
echo -e "\033[0;34m║\033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram  \033[1;31m \033[1;36mNucleos: \033[1;37m$_core\033[0m     \033[0;34m║"
echo -e "\033[0;34m║\033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usor  \033[1;31m \033[1;36mEm uso: \033[1;37m$_usop\033[0m      \033[0;34m║"  
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
echo -e "\033[0;34m║\033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser       \033[0;34m║"
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
echo -e "\033[0;34m║\033[1;32mBADVPN-PRO/UDP \033[1;37m$stsu      \033[1;31m              \033[1;31m  \033[1;32mLIMITADOR-SSH \033[1;37m$stsl   \033[0;34m║"
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mCRIAR USUARIO \033[0;31m          [\033[1;36m15\033[0;31m] \033[1;37m• \033[1;37mSPEEDTEST  \033[0;34m         ║"       
echo -e "\033[0;34m║\033[0;31m[\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mCRIAR TESTE         \033[0;31m    [\033[1;36m16\033[0;31m] \033[1;37m• \033[1;37mBANNER  \033[0;34m            ║"         
echo -e "\033[0;34m║\033[0;31m[\033[1;36m03\033[0;31m] \033[1;37m\033[1;37m• \033[1;37mREMOVER USUARIO \033[0;31m        [\033[1;36m17\033[0;31m] \033[1;37m• \033[1;37mTRAFEGO \033[0;34m            ║" 
echo -e "\033[0;34m║\033[0;31m[\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mMONITOR ONLINE \033[0;31m         [\033[1;36m18\033[0;31m] \033[1;37m• \033[1;37mOTIMIZAR  \033[0;34m          ║"      
echo -e "\033[0;34m║\033[0;31m[\033[1;36m05\033[0;31m] \033[1;37m• \033[1;37mMUDAR DATA \033[0;31m             [\033[1;36m19\033[0;31m] \033[1;37m• \033[1;37mBACKUP  \033[0;34m            ║"         
echo -e "\033[0;34m║\033[0;31m[\033[1;36m06\033[0;31m] \033[1;37m• \033[1;37mALTERAR LIMITE \033[0;31m         [\033[1;36m20\033[0;31m] \033[1;37m• \033[1;37mFERRAMENTAS  \033[0;34m       ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m07\033[0;31m] \033[1;37m• \033[1;37mMUDAR SENHA \033[0;31m            [\033[1;36m21\033[0;31m] \033[1;37m• \033[1;37mLIMITER  \033[0;34m           ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m08\033[0;31m] \033[1;37m• \033[1;37mREMOVER EXPIRADOS \033[0;31m      [\033[1;36m22\033[0;31m] \033[1;37m• \033[1;37mMENU TUNING  \033[0;34m       ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m09\033[0;31m] \033[1;37m• \033[1;37mRELATORIO DE USUARIOS \033[0;31m  [\033[1;36m23\033[0;31m] \033[1;37m• \033[1;37mMENU FIREWALL  \033[0;34m     ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m10\033[0;31m] \033[1;37m• \033[1;37mMODO DE CONEXAO \033[0;31m        [\033[1;36m24\033[0;31m] \033[1;37m• \033[1;37mINFO VPS  \033[1;31m>\033[1;33m>\033[1;32m>\033[0m  \033[0;34m     ║" 
echo -e "\033[0;34m║\033[0;31m[\033[1;36m11\033[0;31m] \033[1;37m• \033[1;37mCRIAR MEMORIA SWAP \033[0;31m     [\033[1;36m25\033[0;31m] \033[1;37m• \033[1;37mONLINE APP $stson\033[0;31m  \033[0;31m  \033[0;34m   ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m12\033[0;31m] \033[1;37m• \033[1;33mMENU PRO \033[0;31m               [\033[1;36m26\033[0;31m] \033[1;37m• \033[1;37mBOT TELEGRAM $stsbot\033[0;31m \033[0;31m  \033[0;34m  ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m13\033[0;31m] \033[1;37m• \033[1;33mPROXY DTUNNEL \033[0;31m          [\033[1;36m27\033[0;31m] \033[1;37m• \033[1;37mMAIS \033[1;31m>\033[1;33m>\033[1;32m>\033[0m  \033[0;34m          ║"
echo -e "\033[0;34m║\033[0;31m[\033[1;36m14\033[0;31m] \033[1;37m• \033[1;33mOTIMIZADOR-EXTREMER \033[0;31m    [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mSAIR \033[1;32m<\033[1;33m<\033[0;31m<\033[1;31m  \033[0;34m          ║"
echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╝\033[0m"
echo -e "\033[0;34m║\033[0;36m╭─────────────────╮ ╭─────────────────╮ ╭─────────────────╮\033[0m"
echo -e "\033[0;34m║\033[1;33m  C \033[1;36m➤ \033[47;1;36m CHECKUSER \033[0;31m     \033[1;33mB \033[1;36m➤ \033[47;1;36m BADVPN \033[0;31m     \033[1;33m    V \033[1;36m➤ \033[47;1;36m V2RAY \033[0m"
echo -e "\033[0;34m║\033[0;36m╰─────────────────╯ ╰─────────────────╯ ╰─────────────────╯\033[0m"
echo -ne "\033[0;34m╚➤ \033[0;31m INFORME UMA OPÇÃO \033[1;33m:"; read x
case "$x" in 
   1 | 01)
   clear
   criarusuario
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   2 | 02)
   clear
   criarteste
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   3 | 03)
   clear
   remover
   sleep 3
   ;;
   4 | 04)
   clear
   sshmonitor
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;      
   5 | 05)
   clear
   mudardata
   sleep 3
   ;;
   6 | 06)
   clear
   alterarlimite
   sleep 3
   ;; 
   7 | 07)
   clear
   alterarsenha
   sleep 3
   ;;
   8 | 08)
   clear
   expcleaner
   echo ""
   sleep 3
   ;;     
   9 | 09)
   clear
   infousers
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   10)
   conexao
   exit;
   ;;
   11)
   swapmemory
   ;;
   12)
   menub2
   ;;
   13)
   bash <(curl -sL https://raw.githubusercontent.com/PhoenixxZ2023/proxy/main/install.sh)
   ;;
   14)
   wget "https://raw.githubusercontent.com/hawshemi/Linux-Optimizer/main/linux-optimizer.sh" -O linux-optimizer.sh && chmod +x linux-optimizer.sh && bash linux-optimizer.sh   
   ;;
   15)
   clear
   velocity
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   16)
   clear
   banner
   sleep 3
   ;;
   17)
   clear
   echo -e "\033[1;32mPARA SAIR CLICK CTRL + C\033[1;36m"
   sleep 4
   nload
   ;;
   18)
   clear
   otimizar
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   19)
   userbackup
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   20)
   clear
   utili
   ;;
   21)
   limit_ssh
   ;;
   22)
   mtuning
   ;;
   23)
   fr
   ;;
   24)
   clear
   detalhes
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;; 
   25)
   onapp_ssh   
   ;;
   26)
   botssh   
   ;;
   27)
   menu2
   ;;
   0|00)
   echo -e "\033[1;31mSaindo...\033[0m"
   sleep 2
   clear
   exit;
   ;;
   C | c)
   checkers
   ;;
   B | b)
   clear
   menub
   exit;
   ;;
   V | v)
   v2raymanager 
   ;;
   *)
   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
   sleep 2
esac
done
}
menu
#fim
