#!/bin/bash
clear
echo -e "\033[01;34m╔══════════════════════════════════════════════╗\033[0m"
echo -e "\033[01;34m╠══════════════════════════════════════════════╣\033[0m"
echo -e "\033[01;34m║\E[44;1;47m             MENU SSH-PLUS PRO                \E[0m\033[0;34m║"
echo -e "\033[01;34m╠══════════════════════════════════════════════╣\033[0m"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m01\033[0;31m]\033[1;32m ➩  \033[1;33mINSTALAR UDP-CUSTOM \033[01;34m                  ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m02\033[0;31m]\033[1;32m ➩  \033[1;33mABRIR MENU UDP-CUSTOM \033[01;34m                ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m03\033[0;31m]\033[1;32m ➩  \033[1;33mINSTALAR SLOW-UDP EVOZI \033[01;34m              ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m04\033[0;31m]\033[1;32m ➩  \033[1;33mINSTALAR WIREGUARD \033[01;34m                   ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m05\033[0;31m]\033[1;32m ➩  \033[1;33mINSTALAR OPENVPN-PRO \033[01;34m                 ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m06\033[0;31m]\033[1;32m ➩  \033[1;33mINSTALAR WS-EPRO \033[01;34m                     ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m07\033[0;31m]\033[1;32m ➩  \033[1;33mINSTALAR HYSTERIA-EVOZI V2 \033[01;34m           ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m08\033[0;31m]\033[1;32m ➩  \033[1;33mINSTALAR PSIPHON \033[01;34m                     ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m09\033[0;31m]\033[1;32m ➩  \033[1;33mUTILIZAR VPS-OTIMIZADOR \033[01;34m              ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m10\033[0;31m]\033[1;32m ➩  \033[1;33mINSTALAR HYSTERIA-PRO \033[01;34m                ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m11\033[0;31m]\033[1;32m ➩  \033[1;33mINSTALAR UDP-HYSTERIA(V1-V2) \033[01;34m         ║"
echo -e "\033[01;34m║\033[0;31m[\033[1;36m00\033[0;31m]\033[1;32m ➩  \033[1;33mSAIR \033[01;34m                                 ║"
echo -e "\033[01;34m╠══════════════════════════════════════════════╝\033[0m"
tput civis
echo -ne "\033[1;34m╰━━━━━━━━❪\033[1;32mSELECIONE UMA OPÇÃO\033[1;33m\033[1;31m\033[1;37m":; read x
case $x in
1 | 01)
    clear
    sudo wget https://raw.githubusercontent.com/thefather12/UDP-PRO/main/install.sh; chmod +x install.sh; ./install.sh
    ;;
2 | 02)
    udp
    ;;
3 | 03)
    wget -N --no-check-certificate https://raw.githubusercontent.com/evozi/hysteria-install/main/slowudp/slowudp.sh && bash slowudp.sh
    ;;
4 | 04)
    bash <(curl -Ls https://raw.githubusercontent.com/Azumi67/FRP-Wireguard/main/wire2.sh --ipv4)
    ;;
5 | 05)
    bash <(curl -sL https://raw.githubusercontent.com/wnetx9/OpenVPN/master/openvpn-install.sh)
    ;;
6 | 06)
    bash <(curl -sL https://raw.githubusercontent.com/wnetx9/ws-epro/main/install.sh)
    ;;
7 | 07)
    wget -N --no-check-certificate https://raw.githubusercontent.com/evozi/hysteria-install/main/hy2/hysteria2.sh && bash hysteria2.sh
    ;;
8 | 08)
    psiphon.sh
    ;;
9 | 09)
    apt install curl -y && bash <(curl -s https://raw.githubusercontent.com/opiran-club/VPS-Optimizer/main/optimizer.sh --ipv4)
    ;;
10 | 10)
    wget https://github.com/thefather12/UDPHISTERIA/raw/main/install.sh; chmod +x install.sh; ./install.sh
    ;;
11 | 11)
    wget --no-cache https://github.com/rudi9999/UDPMOD/raw/main/install.sh; chmod +x install.sh; ./install.sh    
    ;; 
0 | 00)
    clear
    menu
    ;;
*)
    echo -e "\033[1;31mOpção invalida !\033[0m"
    sleep 2
    ;;
esac
