#!/bin/bash

# Set the hexadecimal value of the number of CPUs to the rps_cpus file of the eth0 network interface's receive queue
echo "obase=16;2^$(nproc)-1" | bc > /sys/class/net/eth0/queues/rx-0/rps_cpus

# Set the hashsize parameter of the nf_conntrack module to 16384
echo 16384 > /sys/module/nf_conntrack/parameters/hashsize

# Set the number of flow IDs allocated per receive queue to 16384 for the eth0 interface
echo 16384 > /sys/class/net/eth0/queues/rx-0/rps_flow_cnt

# Set the Timestamp Counter (TSC) as the current clock source for the system
echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource

# Disable transparent huge pages (THP) in the kernel's memory management settings
echo never > /sys/kernel/mm/transparent_hugepage/enabled
